site_name: AEG Ops Doc
site_author: Tony Gilkerson
pages:
  - Home: index.md
  - CI/CD: cicd.md
  # - CI/CD:
  #   - Create Cluster: cicd/create-cluster.md
  #   - Prerequisite Setup: cicd/prerequisite-setup.md
  #   - Utility: cicd/util.md
  - About: about.md
  # - Example Grouping 1:
  #   - Sub page1: grp1/page1.md
  #   - Sub page2: grp1/page2.md
  #   - Sub page3: grp1/page3.md
#theme: readthedocs
