site_name: AEG Ops Doc
site_author: Tony Gilkerson
pages:
  - Home: index.md
  - Monitoring: mon-log-scale.md
  - CI/CD::
    - Toolkit 2.4 CI/CD: cicd/cicd-toolkit24.md
    - Toolkit 2.6 JenkinX: cicd/jx-toolkit26.md
    - JenkinsX Accelerate Deck: cicd/jx-accelerate-deck.md
  - About: about.md
  - Reference: ref.md
#theme: readthedocs
